My portafolio and linked-1
ernestinscastellet/dam1-2024-portfolio pull request #10
Opened 2024-01-14 20:31 UTC by Ygamer123

.

2024-01-15 11:58 UTC, ernestinscastellet requested changes

2024-01-15 11:58 UTC, ernestinscastellet commented on Index.html
> +<ul>
Please add your link to the existing list instead of starting a new list

2024-01-15 16:54 UTC, HikaruRyu requested changes
Make a Css

2024-01-29 16:52 UTC, HikaruRyu approved these changes

2024-01-29 17:30 UTC, merged