Curriculum i Link a l'Index Javi
ernestinscastellet/dam1-2024-portfolio pull request #12
Opened 2024-01-15 14:06 UTC by Javi-Martin-B

He afegit el meu "portfolio" i el link de l'html.

2024-01-15 16:42 UTC, Sheima177 requested changes
compte amb els "br" duplicats i no tancats

2024-01-15 16:42 UTC, Sheima177 commented on portfolios/javi.html
> +    <br>
Compte! br repetit i no tancat

2024-01-15 16:42 UTC, Sheima177 requested changes
cal possar una imatge i fer el CSS

2024-01-15 17:22 UTC, Sheima177 approved these changes

2024-01-29 16:31 UTC, ernestinscastellet approved these changes
Ho veig be!

2024-01-29 17:03 UTC, merged