Portafolio Marta
ernestinscastellet/dam1-2024-portfolio pull request #5
Opened 2024-01-12 14:34 UTC by martavaliente

2024-01-13 10:55 UTC, ernestinscastellet requested changes
Hola Marta,
Bona feina!
Cal afegir un enllaç a la pagina principal

2024-01-13 10:55 UTC, ernestinscastellet commented on portfolios/curriculum/curriculum.html
> +    <style>
Si poses el css en un fitxer a part llavors no fa falta que estigui repetit

2024-01-13 10:55 UTC, ernestinscastellet commented on portfolios/curriculum/curriculum.css
> +*{
El color de fons no es pot posar a * sino a un element com pot ser body

2024-01-13 10:55 UTC, ernestinscastellet commented on portfolios/curriculum/curriculum.html
> +    <header class="color">
Els nomes de classes han de ser mes indicatius.
Per exemple `class="fons-blau"` indica que l'element tindra un fons de color blau

2024-01-13 10:55 UTC, ernestinscastellet commented on portfolios/curriculum/curriculum.html
> +        <p class="color">Ctra. de Vic, 16 08241 Manresa, Barcelona </p>
No hauria de ser necessari aplicar el color a cada element individualment. Si l'element pare te l'estil corresponent els seus fills també el tindrien

2024-01-15 16:33 UTC, Sheima177 requested changes
Falta fegir la teva url de portfoli a l'Index

2024-01-15 16:34 UTC, martavaliente commented on portfolios/curriculum/curriculum.html
> +    <header class="color">
Ja ho he canviat

2024-01-15 17:19 UTC, ernestinscastellet approved these changes
Esta be pero pots millorar les coses que hem parlat

2024-01-15 17:32 UTC, Sheima177 approved these changes

2024-01-15 17:50 UTC, merged