PortafolioElia
ernestinscastellet/dam1-2024-portfolio pull request #7
Opened 2024-01-12 15:29 UTC by epermisan

2024-01-13 10:45 UTC, ernestinscastellet requested changes
Hola Elia, t'he deixat alguns comentaris amb coses per millorar.
Siusplau revisa el teu document

2024-01-13 10:45 UTC, ernestinscastellet commented on portfolios/PortafolioElia.html
> +<cap>
Html funciona en anglès

2024-01-13 10:45 UTC, ernestinscastellet commented on portfolios/PortafolioElia.html
> +<html  lang =" es " >
Revisar els espais ' '.
Hauria de quedar aixi: `<html lang="es">`
Aquest comentari serveix per tot el document

2024-01-13 10:45 UTC, ernestinscastellet commented on portfolios/PortafolioElia.html
> +    </encapçalament >
Aquest element <encapçalament> no existeix en html

2024-01-13 10:45 UTC, ernestinscastellet commented on portfolios/PortafolioElia.html
> +    <header  class =" color " >
Aquesta class="color" no fa res

2024-01-15 16:39 UTC, AlexSitja requested changes
Falta el teu enllaç al index al portfolio.
Hi han bastants espais en blanc en general.

2024-01-15 16:46 UTC, AlexSitja requested changes
Falta CSS

2024-01-15 18:02 UTC, AlexSitja approved these changes

2024-01-16 09:31 UTC, ernestinscastellet requested changes

2024-01-16 09:31 UTC, ernestinscastellet commented on portfolios/epermisan/PortafolioElia.html
> +<!DOCTYPE html >
Hola Elia, veig molts errors de format de codi en aquest document.
Espais dobles i potsats on no toca, etc. Si us plau revisa-ho.
Pots demanar ajuda a algun company de l'equip de qualitat perque et donin un cop de ma

2024-01-29 17:17 UTC, ernestinscastellet approved these changes

2024-01-29 17:32 UTC, merged